require('materialize-css/dist/css/materialize.css');
require('webui-popover/dist/jquery.webui-popover.css');
require('material-design-icons/iconfont/material-icons.css');
require('./client/style.css');
window.jQuery = window.$ = require('jquery');
require('angular');
require('materialize-css/dist/js/materialize.js');
require('angular-ui-router');
require('angular-materialize');
require('webui-popover/dist/jquery.webui-popover.js');
